import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.scss'

import Form from '../../components/forms'
import supabase from '../../supabaseLib'
import prisma from '../../prisma'
import Nav from '../../components/nav'
import Footer from '../../components/footer'
import { newPageProps } from '../../type'



const NewBug: NextPage<newPageProps> = ({user, currUser}) => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bug.ico" />
      </Head>

       <main className={styles.main}>
        {/* <h1>{user.email}</h1> */}
        <Nav page="New Report" user={user.user_metadata}/>
        <Form isNewBug={true} author={user.id} currUserMetadata={currUser}/>
      </main>

      <Footer />
    </div>
  )
}

export default NewBug

export async function getServerSideProps({ req }:any) {
  const { user } = await supabase.auth.api.getUserByCookie(req)
  
  if (!user) {
    // If no user, redirect to index.
    return { props: {}, redirect: { destination: '/', permanent: false } }
  }
  const currUser = await prisma.user?.findUnique({
    where:{ 
      id:user.id
    }
  })
  // If there is a user, return it.
  return { props: { user, currUser } }
}