import prisma from '../../prisma'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect, useRef } from 'react'
import styles from '../../styles/Home.module.scss'
import fnt from '../../styles/Fonts.module.scss'
import supabase from '../../supabaseLib'
import { bugType } from '../../type'
import Nav from '../../components/nav'
import { ModifyButton, DeleteButton } from '../../components/actionButtons'
import Footer from '../../components/footer'

const viewBug:NextPage = ({bugInfo, user, currUserPrivileges}:any) => {
    const [bug, setBug] = useState<bugType>()
    useEffect(() => {
      setBug(JSON.parse(bugInfo))
        
    },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bug.ico" />
      </Head>

      <main className={`${styles.main} dark:text-white`}>
        <Nav page={`${bug?.title} Bug Report`} user={user.user_metadata}/>
        <div className="w-full px-2 my-2">
            {bug?.url ? 
              <div>
                  <Image src={bug.url} alt={`${bug.title} screenshot`} layout="responsive" width="200" height="200"/>
              </div>
          :null}
          <div>
              <div className="py-3 bg-black/5 dark:bg-white/5">
                  <h2 className={`${fnt.title__font} text-2xl`}>Description</h2>
                  <p>{bug?.description}</p>
              </div>
              <div className="py-3 bg-black/10 dark:bg-white/10">
                  <h2 className={`${fnt.title__font} text-2xl`}>Location</h2>
                  <p>{bug?.location}</p>
              </div>
              <div className="py-3 bg-black/5 dark:bg-white/5">
                  <h2 className={`${fnt.title__font} text-2xl`}>How to replicate</h2>
                  <p>{bug?.processToReplicate}</p>
              </div>
          </div>
          <div>
              <div className="py-3 bg-black/10 dark:bg-white/10">
                  <h2 className={`${fnt.title__font} text-2xl`}>Author</h2>
                  <p>{bug?.author}</p>
              </div>
              <div className="py-3 bg-black/5 dark:bg-white/5">
                  <h2 className={`${fnt.title__font} text-2xl`}>Resolved</h2>
                  <p>{bug?.isResolved ? 'Yes' : 'No'}</p>
              </div>
              <div className="py-3 bg-black/10 dark:bg-white/10">
                  <h2 className={`${fnt.title__font} text-2xl`}>Priority</h2>
                  <p>{bug?.priorityStatus}</p>
              </div>
              <div className="py-3 bg-black/5 dark:bg-white/5">
                  <h2 className={`${fnt.title__font} text-2xl`}>Resolved by</h2>
                  <p>{bug?.resolvedBy ? bug?.resolvedBy  : 'No one resolved this bug yet'}</p>
              </div>
              <div className="py-3 bg-black/10 dark:bg-white/10">
                  <h2 className={`${fnt.title__font} text-2xl`}>Reported on</h2>
                  <p>{bug?.createdAt}</p>
              </div>
              <div className="py-3 bg-black/5 dark:bg-white/5">
                  <h2 className={`${fnt.title__font} text-2xl`}>Last modification</h2>
                  <p>{bug?.updatedAt}</p>
              </div>
              <div className="flex justify-center items-center mt-3">
                <ModifyButton bugId={bug?.id} isPrivilege={currUserPrivileges.allowedToDeleteBugReport}/>
                <DeleteButton bugId={bug?.id} isPrivilege={currUserPrivileges.allowedToDeleteBugReport}/>
              </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}

export default viewBug

export async function getServerSideProps({ req, query }:any) {
    
  const { user } = await supabase.auth.api.getUserByCookie(req)
  
  if (!user) {
    // If no user, redirect to index.
    return { props: {}, redirect: { destination: '/', permanent: false } }
  }

  //info about bug
  const bugInfo = JSON.stringify(await prisma.current_bug?.findUnique({
      where:{
          id: parseInt(query.bug)
      }
  })) 
  
  const currUserPrivileges = await prisma.user.findUnique({
    where:{
      id: user.id
    },
    select:{
      allowedToModifyBugReport: true,
      allowedToDeleteBugReport: true
    }
  })

  return{
    props:{ bugInfo, user, currUserPrivileges }
  }
}